### ISSUE TITLE
feature request: new store type 'none'

### ISSUE THREAD

**Issue by anzolo** [arash16/nuxt-ssr-cache#15]
It will be good for local development. Developer can generate part of nuxt config like this:  

> cache: {
>     useHostPrefix: true,
>     pages: [
>       '/',
>     ],
>     store: {
>       type: isDevelopment?'none':'memory',
>       max: 100,
>       ttl: 60,
>     },
>   },

as described in module that you used https://www.npmjs.com/package/cache-manager 

> Development environment
> You may disable real caching but still get all the callback functionality working by setting none store.

**Comment by arash16** [comment]
Use something like this:
```
cache: !isDevelopment && {
    useHostPrefix: true,
    pages: [
    	'/',
    ],
    store: {
        type: 'memory',
        max: 100,
        ttl: 60,
    },
}
```

**Comment by arash16** [comment]
Also you could conditionally return empty `pages` property.
