### ISSUE TITLE
TypeError: Cannot read property 'renderRoute' of undefined

### ISSUE THREAD

**Issue by panchenyu0928** [arash16/nuxt-ssr-cache#17]
nuxtjs v2.10.1

npm run build

node_modules/nuxt-ssr-cache/lib/middleware.js:63
nuxt.renderer is undefined

https://github.com/nuxt/nuxt.js/issues/6519#issuecomment-539365023
https://github.com/nuxt/nuxt.js/issues/6532#issuecomment-539505819

**Comment by aldarund** [comment]
that should be fixed by https://github.com/arash16/nuxt-ssr-cache/pull/16

**Comment by panchenyu0928** [comment]
@arash16 Thank you！😊

**Comment by frederic117** [comment]
I still got the problem :(
