### ISSUE TITLE
How can I clear the page Cache when i need to update the cachePage

### ISSUE THREAD

**Issue by Paulhejia** [arash16/nuxt-ssr-cache#2]
I use  memory mode , when i need to clear cache and i can not see  the api from docs.

**Comment by arash16** [comment]
@Paulhejia 
could explain your use-case a little more please?
to clear the whole cache or clear only some pages?
also where (what context) are you going to do so?
caching happens before any page life-cycle (asyncData, created, etc) gets called, I could add some helper functions to context.req object to clear cache for some specific routes. Is that useful for you?

**Comment by amismailz** [comment]
Hope this will be done soon, is there an estimate?
Also if you have a workaround to invalidate specific pages cache please advice.
Thanks.
