### ISSUE TITLE
How to determine dynamic version

### ISSUE THREAD

**Issue by isuke01** [arash16/nuxt-ssr-cache#27]
Hey,
I know I can set `version: pkg.version,`but it is inside `nuxt.config`. So to change it I have to reload app. In my case Im using dynamic pages from API Backend. I know current version in API, 
Api update version of pages every time someone add page etc. 

So question is:
Can I somehow set version dynamically, and without reloading nuxt app on server? 
Like some server middleware?

**Comment by lww555** [comment]
what is pkg.version? version in  package.json ?

**Comment by isuke01** [comment]
I copied it from docs. But I think it might be e.g packade version, like app version in this case, does not matter to my question actually. Since `nuxt.config` is loaded during startup/reload app on server

**Comment by arash16** [comment]
I guess you can implement a custom `key` function and use your version as part of the generated key. This cache module is executed before anything else inside nuxt and you can't access it inside nuxt (middleware or components etc).
