### ISSUE TITLE
[question] Are there plans to add Cache Headers usage

### ISSUE THREAD

**Issue by martyzz1** [arash16/nuxt-ssr-cache#28]
e.g.  to support if-modified-since or if-not-match?

In order to do this, the cached page, would also need to store an etag value and/or a last-modified time...
Then a request can be compared to the stored values and an appropriate 304 response could be returned...

This would then allow CDN's to cache pages, but have clients still check if the content is updated.

**Comment by arash16** [comment]
No, this package aims to **not render** at all and **reduce load** on server. `if-modified-since` requires to actually render the page on subsequent requests, to calculate hash and compare against etag. 

Btw such cache headers could be easily provided by a reverse-proxy like nginx.

**Comment by martyzz1** [comment]
Hmmm... I might have misunderstood the purpose of this package. I was under the impression this will cache the serverside render of a path/route.  Meaning on subsequent page views the path/route can be returned from cache?
