### ISSUE TITLE
The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by panchenyu0928** [arash16/nuxt-ssr-cache#5]
/lib/middleware.js
if config.cache.useHostPrefix === true
context.req.hostname is undefined

**Comment by arash16** [comment]
@panchenyu0928 I guess you're not using express, and hostname remains undefined.
express uses 'X-Forwarded-Host' header field (if configured to trust proxy) to provide that field.
I have fixed it to use req.host if req.hostname is not provided, but if you're behind reverse proxy, It won't have a meaning value.

**Comment by arash16** [comment]
Also if you're not serving multiple domains, disabling `useHostPrefix` saves you some memory.

**Comment by panchenyu0928** [comment]
@arash16 Thank you！😊
