### ISSUE TITLE
Memcached support?

### ISSUE THREAD

**Issue by 1hakr** [arash16/nuxt-ssr-cache#7]
Do you have plans to add memcached? I have tried to add it but it doesnt seem to work. I would love to see that implemented.

**Comment by arash16** [comment]
@1hakr sure, in a day or two I'll add it.

**Comment by 1hakr** [comment]
@arash16 thanks a lot! Eagerly waiting for it.

**Comment by arash16** [comment]
@1hakr just published it, let me know if everything works as expected.

**Comment by 1hakr** [comment]
I tried i but i'm getting this error 

```
 ERROR  Cannot read property 'isCacheableValue' of undefined                                                                                                    17:58:01

  at MemcachedClient.isCacheableValue (node_modules/cache-manager-memcached-store/index.js:143:20)
  at node_modules/cache-manager/lib/multi_caching.js:228:22
  at node_modules/async/lib/async.js:181:20
  at Object.async.forEachOf.async.eachOf (node_modules/async/lib/async.js:233:13)
  at Object.async.forEach.async.each (node_modules/async/lib/async.js:209:22)
  at Object.setInMultipleCaches (node_modules/cache-manager/lib/multi_caching.js:220:15)
  at node_modules/nuxt-ssr-cache/lib/middleware.js:69:17
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

Also i see you have not added any test cases.

**Comment by arash16** [comment]
@1hakr sorry I didn't have time to write tests.
However I did test it with a live beta version of our site and it was working fine.
Could you provide some code, so that I can reproduce that error?

**Comment by 1hakr** [comment]
```
  cache: {
    useHostPrefix: true,
    store: {
      type: 'multi',
      stores: [
        {
          type: 'memory',
          max: 2000,
          ttl: 3600
        },
        {
          type: 'memcached',
          options: {
            hosts: ['127.0.0.1:11211']
          }
        }
      ]
    },
    pages: ['/']
  }
```
The error was happening only when using multiple stores

**Comment by arash16** [comment]
@1hakr it's a bug with underlying library that I have used.
I have fixed it for now and opened a pull request with that library to be fixed.

**Comment by 1hakr** [comment]
Awesome, its working. Thanks a ton @arash16
