### ISSUE TITLE
Feature: cache key control

### ISSUE THREAD

**Issue by gendalf** [arash16/nuxt-ssr-cache#8]
How about to add some function/module in nuxt config, to have ability control cache key and global version without rebuild app.

For examples:
1. Caching by user, cookie session key as additional cache key
2. Caching by app view settings stored in cookies (mobile/desktop, custom layouts, i18n etc)
3. Flush cache if some global data change time point from redis or etc, is grater than cache time

**Comment by arash16** [comment]
@gendalf done.
